production:
  hosts:
    local:
      ansible_ssh_host: 192.168.1.162
    #machine_name_1:
    #  ansible_ssh_host: 172.17.0.2
    #machine_name_2:
    #  ansible_ssh_host: 172.17.0.3
  vars:
    status_root_path: /tmp/
